<?php
/**
 * Created by PhpStorm.
 * User: Neko
 * Date: 2019/1/21
 * Time: 5:48 PM
 */

namespace pdd\request;

class PddDdkGoodsPidGenerateRequest extends PddRequest
{

    /**
     * @var string 要生成的推广位数量，默认为10，范围为：1~100
     */
    public $number = '1';

    /**
     * @var array 推广位名称，例如["1","2"]
     */
    public $p_id_name_list = [];

    public $type = 'pdd.ddk.goods.pid.generate';

    public function getRequestCache(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

}